apiVersion: v1
kind: ConfigMap
metadata:
  name: librespeed-env
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
data:
  TELEMETRY: "true"
  TELEMETRY_LEVEL: "full"
  ENABLE_ID_OBFUSCATION: "true"
  ALLOW_IP_CHANGE: "false"
  DB_TYPE: "mysql"
  DB_HOST: "mysql.db.svc.cluster.local"
  DB_NAME: "librespeed_db"
  DB_USER: "librespeed"
