apiVersion: v1
kind: Secret
metadata:
  name: registrysecret
  namespace: final
data:
  .dockerconfigjson: "ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5yZWJyYWlubWUuY29tIjogewogICAgICAiYXV0aCI6ICJjSFZzYkMxamNtVmtjenBuYkhCaGRDMTJibkJNWDJsMk4xZDRaSHBDTWxGUmRVdEZSUT09IgogICAgfQogIH0KfQo="
type: kubernetes.io/dockerconfigjson
